### ISSUE TITLE
Who are the teaching assistants (TAs) for this course?

### ISSUE THREAD

**Issue by Zian-0427** [GraphPKU/MachineLearning2024#1]

**Comment by Zian-0427** [comment]
I’m Zian Li, one of the TAs and a second-year Ph.D. student at the Institute of Artificial Intelligence, PKU. Please feel free to ask any course-related questions in the github issue section. You can also reach me at zian@stu.pku.edu.cn.

**Comment by Blancokdb** [comment]
I'm Yiding Wang, one of the TAs and a junior student of Tong class, Yuanpei College, PKU. I'm willing to help you with any difficulties you encounter while taking this course. You can also reach me at 2200017439@stu.pku.edu.cn.

**Comment by pengxingang** [comment]
I am Xingang Peng, one of the TAs and a third-year Ph.D candidate at the Insititute of Artificial Intelligence, PKU. Feel free to contact me if you have any questions related to the course. You can also reach me at pengxingang@stu.pku.edu.cn. Enjoy!

**Comment by zxhxgithub** [comment]
I am Xiaohui Zhang,  one of the TAs and a junior student at School of Mathematical Sciences, PKU. Please feel free to contact me if you have any course-related questions. You can also reach me at 2200010821@stu.pku.edu.cn. Hope you can enjoy Machine Learning when taking the course!
