### ISSUE TITLE
关于课后作业3第一题

### ISSUE THREAD

**Issue by jasondayuan** [GraphPKU/MachineLearning2024#17]
助教好，我想确认一下优化得到的\alpha_i或者正样本点和负样本点的数值确定没有给错吗？在(1)中算b的时候用不同的样本点作为支持向量的时候的结果好像差距很大...

**Comment by jasondayuan** [comment]
顺便也想问一下第四题第（2）问的“写出f(x)的对偶形式“是什么意思，f(x)也不是一个优化问题的目标函数啊🤔

**Comment by zxhxgithub** [comment]
有关作业3的第一题，\alpha_i的数值确实存在一定问题，但是不影响计算。在作答时只需按照题干要求，使用第一个样本点作为支撑向量做计算即可。

**Comment by jasondayuan** [comment]
好的，谢谢助教！
