### ISSUE TITLE
Clarification on one statement in class (welcome discussion)

### ISSUE THREAD

**Issue by muhanzhang** [GraphPKU/MachineLearning2024#19]
<img width="1297" alt="image" src="https://github.com/user-attachments/assets/898d24a9-6c9b-4ee8-9744-c1c1a4d268cd">

**Comment by RechargeDeng** [comment]
我有两个问题，第一个是，这个D是原本n个数据的训练集的子集吗，为什么我可以得到一个更加tight的界？第二个问题比较长，我在附带的图片里写了具体问题
![IMG_1738](https://github.com/user-attachments/assets/065a648f-7be9-421c-9e06-2cd5a2ea3ec0)

**Comment by muhanzhang** [comment]
1. D is the set of the original n training data, which is for notation simplicity only. It is an assumption that we can get a tighter bound. The original single-h PAC bound only considers the number and range of random variables, thus is a 
 very loose bound. Here I assume you can get a tighter bound by considering more fine-grained information in D and dichotomy. For this tighter bound, it is shared by all h1, h2, h3 ... generating the same dichotomy on D. 

2. The example I gave is only an intuitive explaination why the union bound on h1, h2, h3 ... overestimate the probability. For the exact reason why the union bound's M can be replaced by growth founction, please refer to the full proof of VC generalization bound (you may refer to the Appendix of book *Learning From Data*).
