### ISSUE TITLE
请问这门课有课堂实录吗？

### ISSUE THREAD

**Issue by Fengbai-Su** [GraphPKU/MachineLearning2024#2]

**Comment by Zian-0427** [comment]
有的，每节课后过两天就会出

**Comment by Fengbai-Su** [comment]
> 有的，每节课后过两天就会出

为什么现在还看不到周三的录播呢？

**Comment by Zian-0427** [comment]
> > 有的，每节课后过两天就会出
> 
> 为什么现在还看不到周三的录播呢？

本科生教学网上的《机器学习》应该已经能看到了，研究生的《机器学习A》还没有同步，可能是技术问题，目前正在和负责老师沟通。

**Comment by Zian-0427** [comment]
更新：由于技术原因，目前研究生同学可能仍无法看到课堂实录。我们已在教学网的“[本课程] - 教学内容”模块中上传了前两次课程的录制链接，供大家临时查看。
