### ISSUE TITLE
Assignment3

### ISSUE THREAD

**Issue by Dora-Xiong** [GraphPKU/MachineLearning2024#20]
请问作业3的第4题，请问题目中要求“给出ai的取值集合”具体是想让我求解什么，是证明算法的收敛性吗？没有太明白。

**Comment by pengxingang** [comment]
你好，这里“给出 $a_i$ 的取值集合“指的是，在一般情况下 $a_i$ 可能取得的数值有哪些，比如 $a_i$ 可能取到实数？还是所有非负整数？还是 $[0,1]$ ？或是其他数集？直接给出一个集合即可。
