### ISSUE TITLE
【作业发布】课后练习-5

### ISSUE THREAD

**Issue by pengxingang** [GraphPKU/MachineLearning2024#22]
同学们好，课后练习5已经发布到教学网上（同时附于该issue中），截止日期为2024年11月22日。本科生同学请按时完成并在【教学网上】提交，作业将计入成绩；研究生同学不强制要求完成，作业不计入成绩，可以作为学习的参考资料。
[课后练习-5.docx](https://github.com/user-attachments/files/17778613/-5.docx)

**Comment by Blancokdb** [comment]
第四题（1）：loss function中 h(x_i) 改为 g^(t)_(x_i)
