### ISSUE TITLE
关于考试范围

### ISSUE THREAD

**Issue by jasondayuan** [GraphPKU/MachineLearning2024#28]
可以问一下周三课上讲到的贝叶斯网络和神经网络在考试范围内吗？

**Comment by wzy2to** [comment]
> 期中考试范围包括到11.13日为止（包括11.13日课）所有内容，除去representer theorem

助教好，上周三课上授课的助教在开始讲“Neural Networks and Backpropagation”部分时说“这个应该算是了解内容”，并且课后也没有上传这部分的PPT。想在确认这一部分的内容是否在考试范围内，谢谢！

**Comment by Zian-0427** [comment]
> > 期中考试范围包括到11.13日为止（包括11.13日课）所有内容，除去representer theorem
> 
> 助教好，上周三课上授课的助教在开始讲“Neural Networks and Backpropagation”部分时说“这个应该算是了解内容”，并且课后也没有上传这部分的PPT。想在确认这一部分的内容是否在考试范围内，谢谢！

Neural Networks and Backpropagation部分不在考试范围内。

**Comment by qiweili00** [comment]
> 期中考试范围包括到11.13日为止（包括11.13日课）所有内容，除去representation theorem

助教好，请问11月20日讲的Ensemble Model是否在考试范围内，谢谢！

**Comment by Zian-0427** [comment]
> > 期中考试范围包括到11.13日为止（包括11.13日课）所有内容，除去representation theorem
> 
> 助教好，请问11月20日讲的Ensemble Model是否在考试范围内，谢谢！

在的

**Comment by learnerljh** [comment]
助教好，请问再生核希尔伯特空间在考试范围内吗
