### ISSUE TITLE
关于Cheat Sheet的要求

### ISSUE THREAD

**Issue by Zian-0427** [GraphPKU/MachineLearning2024#31]
各位同学好，本次考试允许自带一张正反面手写cheat sheet（A4纸大小）。注意，不允许在ipad上手写后打印。考试前助教会对大家自带的cheat sheet进行逐一检查。

**Comment by AheadOFpotato** [comment]
感觉“不打印“的要求不太合理，而且通知得太晚了…已经准备完的cheating sheet还得再抄一遍，很浪费时间。可否检查打印的字体大小/内容是否合理（虽然理解手写和打印的字体也很难给一个统一标准）？

**Comment by pengxingang** [comment]
更新：

各位同学好，本次考试允许自带一张正反面手写cheat sheet（A4纸大小），考试前会对大家自带的cheat sheet进行逐一检查。

注意，cheat sheet请以手写为主；对于打印的cheat sheet，会进行更严格检查，不允许出现明显缩放的字体。

**Comment by lkc233** [comment]
请问什么叫 明显缩放的字体？ 这是没有明确标准的。如果考试前检查不合格会不允许使用cheating sheet吗？即使是手写也可用很细的笔将字写的很小，这样的又如何处理呢？？？

**Comment by muhanzhang** [comment]
关于cheat sheet，我统一回复一下。请用A4纸手写，不允许打印平板上的内容。如果已经用平板写好了cheat sheet不想重新用纸写的同学，我们会严格检查你打印的内容，不允许出现明显缩放（比如压缩到超过正常纸笔能写出的粗细，这样对纸笔写的同学不公平），也不允许复制别人的cheat sheet，发现的话将直接没收不允许使用。还没有做cheat sheet的同学，请严格纸笔手写。

允许纸笔手写cheat sheet的目的是为了让大家自己整理一遍知识点，这个过程对掌握知识非常的有帮助；如果允许打印，那么有些人就会copy paste自己的课堂笔记，甚至直接打印别人的cheat sheet，背离了初衷。如果你不想risk cheat sheet完全被没收的风险，那么请坚持纸笔手写。
