### ISSUE TITLE
关于考试范围

### ISSUE THREAD

**Issue by Zian-0427** [GraphPKU/MachineLearning2024#32]
各位同学好，期中考试的考试范围应当是到11.20日（包括11.20日课，即考试前最后一次课；上一个issue中表述有误）。不包括representation theorem与Neural Networks and Backpropagation的内容。

**Comment by Marshmallow822** [comment]
难崩，刚把cheet sheet写满就改考试范围了

**Comment by Marshmallow822** [comment]
难崩，刚把cheat sheet写满就改考试范围了

**Comment by ashen-ljh** [comment]
这样真的合规吗。。。临考试前两天通知更新范围是否有点

**Comment by muhanzhang** [comment]
助教上一则通知有误，所有信息以我课堂上的通知为最终标准。考试内容包括期中前最后一次上课（即20号）之前的所有内容（除了representer theorem、RKHS相关的）。

**Comment by muhanzhang** [comment]
考试范围包括20号课上的内容（Boosting, Bayesian Networks），不含neural networks and backpropagation。
