### ISSUE TITLE
作业三第二题疑问

### ISSUE THREAD

**Issue by zjizhe** [GraphPKU/MachineLearning2024#34]
请问作业三这道题加入松弛变量后的支持向量是如何判断的呢？答案中对于$x_3$,$x_4$是支持向量的解释没有看明白。
![Snipaste_2024-11-26_19-10-45](https://github.com/user-attachments/assets/a59ec6f6-d270-4a00-b97b-27726dc65619)

答案：
![Snipaste_2024-11-26_19-11-10](https://github.com/user-attachments/assets/a2d4f5ee-062b-49e5-8069-1dfbec741f2c)

**Comment by CHERRY-ui8** [comment]
x_3是SV是因为：x_3的松弛变量大于0，说明x_3是active的，对决策超平面起作用了；
x_4是SV是因为：x_4是数据集中的唯一一个负例点，而正负例中都至少需要有一个SV（课后练习2的第四题也证明过这件事，虽然那道题是硬间隔，但是逻辑上是完全一样的）
希望解答了你的问题:D
