### ISSUE TITLE
逻辑回归lab中注释疑似有误

### ISSUE THREAD

**Issue by Cgfyufsygsm** [GraphPKU/MachineLearning2024#38]
`LogisticRegression` 类中 `predict(x)` 函数中的注释

```python
# TODO: first, you should add bias term to x
```

疑似有误，根据 `autograder.py` 第 19 行以及 `predict(x)` 函数中注释给出的 `x` 的类型，传进给 `predict` 的 `x` 应该是已经添加了 bias term 的，无需重复添加。

**Comment by Cgfyufsygsm** [comment]
额，而且似乎在后面 `y_train_pred = LR.predict(x_train)` 这个地方传进去的 x 又是没有添加 bias term 的了。可否请助教团队进行一下修复

**Comment by Cgfyufsygsm** [comment]
而且在最后部分的

```python
train_acc = compute_accuracy(x_train, y_train, LR)
print("Train accuracy: {}".format(train_acc))

test_acc = compute_accuracy(x_test, y_test, LR)
print("Test accuracy: {}".format(test_acc))
```

中，`compute_accuracy` 函数应该是只有两个参数的吧，ipynb 文件中传入了三个导致报错了，请问这个是不是需要修复一下

**Comment by Cgfyufsygsm** [comment]
> 而且在最后部分的
> 
> ```python
> train_acc = compute_accuracy(x_train, y_train, LR)
> print("Train accuracy: {}".format(train_acc))
> 
> test_acc = compute_accuracy(x_test, y_test, LR)
> print("Test accuracy: {}".format(test_acc))
> ```
> 
> 中，`compute_accuracy` 函数应该是只有两个参数的吧，ipynb 文件中传入了三个导致报错了，请问这个是不是需要修复一下

而且这个 `compute_accuracy` 不是应该传入的是 `y` 的 pred 和 gt 吗，这里为啥是这么写的

**Comment by zxhxgithub** [comment]
感谢同学指出，我们已经修正了代码框架，并且在教学网上传了最新的lab压缩包。
