### ISSUE TITLE
KNN lab 中代码框架疑似有误

### ISSUE THREAD

**Issue by Cgfyufsygsm** [GraphPKU/MachineLearning2024#39]
`KNN_predict` 的返回部分中，代码框架内给出的是 `return np.array(predictions)`，但是 `autograder.py` 中第 32 行中是用 `self.assertListEqual` 来判断正确性的，而其前两个参数的类型应当为 `list` 而不是 `np.array`。如果不对给出的代码进行修改则会报错。

**Comment by zxhxgithub** [comment]
感谢同学指出，我们已经对此进行了修改，并且在教学网上更新了lab压缩包。
