### ISSUE TITLE
关于 AdaBoost Lab 的 test acc 要求

### ISSUE THREAD

**Issue by Cgfyufsygsm** [GraphPKU/MachineLearning2024#41]
请问一下最后要求在测试集上分类准确率是需要大于 70%（ipynb 文件中所说）还是 90%（autograder.py 中）

**Comment by Zian-0427** [comment]
以autograder为准，应是90%；正确实现应该可以达到很高的正确率（～100）

**Comment by Cgfyufsygsm** [comment]
> 以autograder为准，应是90%；正确实现应该可以达到很高的正确率（～100）

好的，感谢！
