### ISSUE TITLE
About assignment 1 q4

### ISSUE THREAD

**Issue by Stanleytowne** [GraphPKU/MachineLearning2024#5]
I see that the problem specifies a **positive number k**. Does this mean that for data $(x_i, y_i)$ with label $y_i = 1$, we should have $w^Tx_i + b > 0$? 
Otherwise, the current description only requires the plane $w^Tx + b = 0$ to be a separating hyperplane, so the data point $(x_i, 1)$ could be on either side of it. If the point $(x_i, 1)$ is 'below' the plane, meaning $w^Tx_i + b < 0$, then the conclusion is not correct.

**Comment by pengxingang** [comment]
Yes, by selecting a separating hyperplane $w^\top x+b=0$, here you can assume that for positive data $(x_i, y_i)$ we have $w^\top x_i + b>0$.

**Comment by Stanleytowne** [comment]
Thanks a lot!
